# site settings
title: Laboratorio Cívico
# email: lab@ciudadanointeligente.org
description: "Experimientos ciudadanos para el cambio social"
baseurl: "http://labcivico.org"
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
# analytics: 'UA-41822715-1'

# build settings
markdown: kramdown
